### PR TITLE
Fixed parse exception when parser has no options

### PR DESCRIPTION
**Pull request by jjst**
List.max will throw an UnsupportedOperationException if the list is
empty.

### CODE REVIEW

**Comment by jjst** [comment]
Hey Brian,

Do you have any plans to release a new version with this fix in?

**Comment by bmc** [comment]
I just checked. These changes should already be in 1.0.3, which is published.

**Comment by jjst** [comment]
Are you sure? I'm using 1.0.3 already and I'm definitely still seeing the bug. I checked the sources for 1.0.3 at http://dl.bintray.com/bmc/maven/org/clapper/argot_2.11/1.0.3/#argot_2.11-1.0.3-sources.jar and https://repo1.maven.org/maven2/org/clapper/argot_2.11/1.0.3/argot_2.11-1.0.3-sources.jar, and the fix isn't there.

BTW, I don't know if could be related, but it looks like 1.0.3 was mistakenly tagged as 1.3.0: https://github.com/bmc/argot/releases

**Comment by bmc** [comment]
I’ll rerelease as 1.0.4, sometime later today. I’ve been known to screw this up, when I’m in a hurry...

**Comment by jjst** [comment]
Haha. No worries at all. Thanks!

**Comment by jjst** [comment]
Any update?

**Pull request merged**
